-- 코드를 작성해주세요
SELECT YEAR(b.DIFFERENTIATION_DATE) AS YEAR , a.ad - b.SIZE_OF_COLONY AS YEAR_DEV, b.ID
FROM ECOLI_DATA b
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS ad, YEAR(DIFFERENTIATION_DATE) as aa
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)a
ON a.aa = YEAR(b.DIFFERENTIATION_DATE)
ORDER BY YEAR,YEAR_DEV